-- MySQL Script generated by MySQL Workbench
-- Чт. 24 нояб. 2016 15:43:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `birthday` DATE NULL DEFAULT NULL COMMENT '',
  `image` BLOB NULL DEFAULT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`author` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `biography` TEXT NULL DEFAULT NULL COMMENT '',
  `person_id` INT UNSIGNED NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`, `person_id`)  COMMENT '',
  INDEX `fk_author_person1_idx` (`person_id` ASC)  COMMENT '',
  CONSTRAINT `fk_author_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `library`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `country_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `country_id` INT UNSIGNED NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_city_country1_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `library`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `district` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `postal_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `city_id` INT UNSIGNED NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_address_city1_idx` (`city_id` ASC)  COMMENT '',
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `library`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `person_id` INT UNSIGNED NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `salt` VARCHAR(45) NOT NULL COMMENT '',
  `address_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `mobile_phone` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `role` ENUM('admin', 'librarian', 'reader') NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`, `person_id`)  COMMENT '',
  INDEX `fk_user_person1_idx` (`person_id` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  INDEX `fk_user_address1_idx` (`address_id` ASC)  COMMENT '',
  UNIQUE INDEX `mobile_phone_UNIQUE` (`mobile_phone` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `library`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `library`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `language` VARCHAR(45) NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `language_UNIQUE` (`language` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`publisher` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `image` BLOB NULL DEFAULT NULL COMMENT '',
  `address_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `fk_publisher_address1_idx` (`address_id` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  CONSTRAINT `fk_publisher_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `library`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book_edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_edition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `page_count` INT NULL DEFAULT NULL COMMENT '',
  `release_year` YEAR NULL DEFAULT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `isbn` INT NULL DEFAULT NULL COMMENT '',
  `language_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `original_language_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `weight` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `bookbinding` ENUM('soft', 'hard') NULL DEFAULT NULL COMMENT '',
  `image` BLOB NULL DEFAULT NULL COMMENT '',
  `publisher_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_book_edition_language1_idx` (`language_id` ASC)  COMMENT '',
  INDEX `fk_book_edition_language2_idx` (`original_language_id` ASC)  COMMENT '',
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC)  COMMENT '',
  INDEX `fk_book_eition_publisher1_idx` (`publisher_id` ASC)  COMMENT '',
  CONSTRAINT `fk_book_edition_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `library`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_edition_language2`
    FOREIGN KEY (`original_language_id`)
    REFERENCES `library`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_edition_publisher1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `library`.`publisher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `book_edition_id` INT UNSIGNED NOT NULL COMMENT '',
  `position` ENUM('store', 'reading_room', 'user') NOT NULL COMMENT '',
  `state` ENUM('excellent', 'good', 'fine', 'bad', 'terribly') NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`, `book_edition_id`)  COMMENT '',
  INDEX `fk_book_book_edition1_idx` (`book_edition_id` ASC)  COMMENT '',
  CONSTRAINT `fk_book_book_edition1`
    FOREIGN KEY (`book_edition_id`)
    REFERENCES `library`.`book_edition` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`rental` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `comment` TEXT NULL DEFAULT NULL COMMENT '',
  `rental_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `return_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `staff_user_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `book_id` INT UNSIGNED NOT NULL COMMENT '',
  `book_state_before` ENUM('excellent', 'good', 'fine', 'bad', 'terribly') NOT NULL COMMENT '',
  `book_state_after` ENUM('excellent', 'good', 'fine', 'bad', 'terribly') NULL DEFAULT NULL COMMENT '',
  `issue` ENUM('ordered', 'denied', 'issued') NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_rental_user1_idx` (`staff_user_id` ASC)  COMMENT '',
  INDEX `fk_rental_user2_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_rental_book1_idx` (`book_id` ASC)  COMMENT '',
  CONSTRAINT `fk_rental_user1`
    FOREIGN KEY (`staff_user_id`)
    REFERENCES `library`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `category_UNIQUE` (`category` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`author_has_book_edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`author_has_book_edition` (
  `author_id` INT UNSIGNED NOT NULL COMMENT '',
  `book_edition_id` INT UNSIGNED NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`author_id`, `book_edition_id`)  COMMENT '',
  INDEX `fk_author_has_book_edition_book_eition1_idx` (`book_edition_id` ASC)  COMMENT '',
  INDEX `fk_author_has_book_edition_author1_idx` (`author_id` ASC)  COMMENT '',
  CONSTRAINT `fk_author_has_book_edition_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `library`.`author` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_has_book_edition_book_eition1`
    FOREIGN KEY (`book_edition_id`)
    REFERENCES `library`.`book_edition` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book_eition_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_eition_has_category` (
  `book_eition_id` INT UNSIGNED NOT NULL COMMENT '',
  `category_id` INT UNSIGNED NOT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`book_eition_id`, `category_id`)  COMMENT '',
  INDEX `fk_book_eition_has_category_category1_idx` (`category_id` ASC)  COMMENT '',
  INDEX `fk_book_eition_has_category_book_eition1_idx` (`book_eition_id` ASC)  COMMENT '',
  CONSTRAINT `fk_book_eition_has_category_book_eition1`
    FOREIGN KEY (`book_eition_id`)
    REFERENCES `library`.`book_edition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_eition_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `library`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
